#cloud-config

hostname: {{hostname}}
fqdn: {{fqdn}}
create_hostname_file: true

users:
  - name: {{user}}
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    lock_passwd: true
    ssh_authorized_keys:
      - {{ssh-key}}
      - {{another-ssh-key}}

ssh_pwauth: false
disable_root: true

growpart:
  mode: auto
  devices: [ '/' ]

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - ca-certificates
  - cloud-utils
  - findutils
  - nginx
  - podman
  - python3-certbot-nginx
